data:
  input:
    text_dir: "data/input/text/"
    images_dir: "data/input/images/"
  output: "data/output/experimental_scenarios/"

spacy:
    model: "en_core_web_md"

evaluation:
    enabled: true
    #scenarios: ["high-precision", "moderate-connectivity", "comprehensive"]
#    scenarios: ["dev_a_precision", "dev_b_balanced", "dev_c_diverse"]
    scenarios: ["dev_a_precision"]
    runs_per_algorithm: 5
    metrics:
      - "total_time"
      - "batch_processing_time"
      - "conflict_frequency"
      - "throughput"
      - "memory_usage"
      - "cpu_utilization"
    output_dir: "data/evaluation/"

database:
  neo4j:
    uri: "bolt://localhost:7687"
    user: "neo4j"
    password: "research123"
    database: "research"


algorithms:
  # 1. SIMPLE SEQUENTIAL BASELINE (Your Control Group)
  simple_baseline:
    name: "Simple Sequential Baseline"
    description: "Minimal sequential processing with no optimization"
    batch_size: 500  # Single batch size for initial testing
    #batch_sizes: [250]  # Array for testing multiple sizes
    # That's it! Intentionally minimal configuration

  # 2. SEQUENTIAL WITH MULTIPLE BATCH SIZES (For comparison)
  simple_parallel:
    name: "Simple Parallel Baseline"
    description: "Naive parallel processing"
    batch_size: 100
    thread_count: 10      # Fixed parallelism
    max_retries: 2            # Maximum retry attempts per failed relationship

  # 4. MIX AND BATCH (Published Algorithm)
  mix_and_batch:
    name: "Mix and Batch Parallel Algorithm"
    description: "Published parallel loading approach with conflict-free partitioning"
    num_partitions: 10
    max_workers: 10
    batch_size: 1000
    hash_digits: 1

  # 5. YOUR ADAPTIVE ALGORITHM (Research Contribution)
  adaptive_dynamic:
    name: "Adaptive Dynamic Batching Algorithm"
    description: "Intelligent conflict-aware dynamic batching with real-time adaptation"
    # Initial parameters (will adapt during execution)
    initial_batch_size: 500
    min_batch_size: 50
    max_batch_size: 2000

    # Adaptation parameters
    conflict_threshold: 0.05  # 5% conflict rate triggers adaptation
    adaptation_rate: 0.3      # How aggressively to adjust
    learning_window: 5        # Batches to consider for adaptation

    # Parallelism control
    initial_parallelism: 4
    min_parallelism: 1
    max_parallelism: 8

    # Conflict prediction
    hub_threshold: 5
    prediction_confidence: 0.8

    # Performance targets
    target_throughput: 1000  # relationships/second
    acceptable_failure_rate: 0.01  # 1% max failure